// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "lo",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "lo",
            targets: ["AppModule"],
            bundleIdentifier: "punk.systems.lo",
            teamIdentifier: "28PK8QN487",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .movieReel),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    dependencies: [
        .package(url: "https://github.com/apple/swift-algorithms.git", "1.2.0"..<"2.0.0"),
        .package(url: "https://github.com/kvyatkovskys/KVKCalendar", "0.6.29"..<"1.0.0"),
        .package(url: "https://github.com/airbnb/HorizonCalendar.git", .branch("master"))
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "Algorithms", package: "swift-algorithms"),
                .product(name: "KVKCalendar", package: "kvkcalendar"),
                .product(name: "HorizonCalendar", package: "horizoncalendar")
            ],
            path: "."
        )
    ]
)